### ISSUE TITLE
How to reset 5.1 HW

### ISSUE THREAD

**Issue by tomklapka** [danielkucera/esp-arduino-ebus#41]
can't connect TX-DISABLE (previously ESP-RX) and GND pins using a wire - there is no pin marked TX-DISABLE anymore.

**Comment by danielkucera** [comment]
Hello, this is a bug. I am preparing a fix in #43 but it is not ready yet.
To reset the device config with current firmware, please disable your wifi temporarily so the device cannot connect. After this the config AP will appear and you can reset the config from there.

**Comment by danielkucera** [comment]
I am sorry to hear that. Would you mind sending it back for analyzing the problem? 
I can give you a refund for the new one.

**Comment by danielkucera** [comment]
I am not going to use it, just to find the root cause.
