### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by adallari1969** [danielkucera/esp-arduino-ebus#51]
Hi
I connected the esp8266-arduino-ebus v5.2 to my ebus
configured the wifi network

the device get the ip, I can ping it 
I can connect to esp-ebus.local port 3334 using telnet - I see unreadable binary data 
but if I try connect to http://esp-ebus.local:5555 i get the error (from browser)
"This page isn’t working192.168.1.132 sent an invalid response.
ERR_INVALID_HTTP_RESPONSE"

If I try to set the esp-bus ip address in the ebusd add on in my Home assistan, I get the error "ERROR: Got unexpected response from the API: Service not enabled"

can you pls help me?

**Comment by adallari1969** [comment]
I also tried the reset, but no changes

**Comment by danielkucera** [comment]
Hello,
which browser?

**Comment by adallari1969** [comment]
Hi
Both chrome and edge

Il Dom 14 Mag 2023, 20:28 Daniel Kucera ***@***.***> ha
scritto:

**Comment by adallari1969** [comment]
hallo,
any feedback from your side?

**Comment by danielkucera** [comment]
Hi @adallari1969 ,
it is related to #39 .
I am still trying to figure out a good way to handle http requests on the status server.
Meanwhile you can use `telnet esp-ebus.local 5555` to check the status server.

**Comment by adallari1969** [comment]
Any browser works whit it?

Il Sab 20 Mag 2023, 23:04 Daniel Kucera ***@***.***> ha
scritto:

**Comment by danielkucera** [comment]
Hm, I was under impression that both Firefox and Chrome works but now I have tested more of them and found out that only Firefox under Linux works.
I'll make the next firmware work with all browsers. For now you can use telnet to check the status:
```
telnet esp-ebus.local 5555
```

**Comment by danielkucera** [comment]
resolved in #64
