### ISSUE TITLE
open http://esp-ebus.local/param to adjust PWM value

### ISSUE THREAD

**Issue by tomm10000** [danielkucera/esp-arduino-ebus#65]
Hello, Before uploading the software, I could set PWM, now I don't know how to enter this option.
I'm trying http://192.168.1.135/param but it doesn't work

**Comment by danielkucera** [comment]
Hello, which HW version do you have?

**Comment by tomm10000** [comment]
> Hello, which HW version do you have?

HW 6.1

```
Chip ID: 543204b78c50, ESP32-C3, rev 4
Hostname: ebus-b78c50
PCB: 20.0
Flash: 4194304
Version: v5.2-dev-3318-g8fc8f3f479
Reset reason: 1
eBUS r/w: 1/0
Host r/w: 4/20
Up time: 216
Free heap: 99168
ebusd connected: yes (inactive)
eBUS signal: no signal
```

**Comment by danielkucera** [comment]
And which software did you upload?

**Comment by tomm10000** [comment]
Through this website, I guess that FW is not correct
https://adapter.ebusd.eu/v5/firmware.en.html

This one update? firmware-fullflash-HW_v5.x-be7bb3.bin
https://github.com/danielkucera/esp8266-arduino-ebus/releases

**Comment by danielkucera** [comment]
Yes, the first one is incorrect, completely different hardware.

Yes, use the one from releases on this page

**Comment by tomm10000** [comment]
Can I upload via USB-C? + NodeMCU PyFlasher

**Comment by tomm10000** [comment]
<img width="1215" alt="Zrzut ekranu 2024-01-31 o 22 14 49" src="https://github.com/danielkucera/esp8266-arduino-ebus/assets/41973859/e3703d8a-5ae7-49a9-9ca7-ee1d01af40a3">

**Comment by tomm10000** [comment]
![IMG_4677](https://github.com/danielkucera/esp8266-arduino-ebus/assets/41973859/48eb72b6-8324-4375-8ede-0ad24b51af30)

**Comment by tomm10000** [comment]
The jumper is also not understandable to me

> power from any adapter 5-24V: remove jumper and connect adapter to VCC and GND pins

![IMG_4679](https://github.com/danielkucera/esp8266-arduino-ebus/assets/41973859/d5dfdb58-82aa-43bc-b3b2-f18a8dca51f3)
![IMG_4678](https://github.com/danielkucera/esp8266-arduino-ebus/assets/41973859/152e3d35-2ed2-425f-bd68-746e930832f3)

**Comment by danielkucera** [comment]
What is the question exactly?

**Comment by tomm10000** [comment]
Which pins are these?
using a wire connect pins PROG and TP3 ( TP3 ?? )
I don't understand it, different markings

> connect your adaptor in a following way (dongle - module):
> 3V3 <-> 3V3
> TX <-> ESP-RX
> RX <-> ESP-TX
> GND <-> GND
>

**Comment by danielkucera** [comment]
This is for the old version. For 6.1 just connect PROG and GND and flash over the USB-C port

**Comment by tomm10000** [comment]
@danielkucera
Thank you for your help

Adds a link to the page where you can upload the firmware firmware-fullflash-HW_v5.x-be7bb3.bin
Address 0x0

https://adafruit.github.io/Adafruit_WebSerial_ESPTool/

**Comment by danielkucera** [comment]
> now I have to upload the software ?

What do you mean by this?

**Comment by tomm10000** [comment]
Does this software still require any update, because I only have this simple configuration panel

Now D1 works OK

> device: 192.168.1.135:3333, TCP, enhanced
> signal: acquired
> symbol rate: 14
> max symbol rate: 22
> reconnects: 1
> masters: 1
> messages: 11
> conditional: 0
> poll: 0
> update: 4
> address 31: master #8, ebusd
> address 36: slave #8, ebusd

**Comment by danielkucera** [comment]
It's all there is. You will need to setup ebusd to connect to your adapter to decode the data.

**Comment by tomm10000** [comment]
> `It's all there is. You will need to setup ebusd to connect to your adapter to decode the data.`

Thank you
There is a connection  :-)

> root@raspberrypi:~# ebusctl info
> version: ebusd 23.3.23.3-29-g2ea20ed8
> device: 192.168.1.135:3335, TCP, enhanced
> signal: acquired
> symbol rate: 25
> max symbol rate: 25
> reconnects: 0
> masters: 3
> messages: 11
> conditional: 0
> poll: 0
> update: 4
> address 03: master #11
> address 08: slave #11
> address 10: master #2
> address 31: master #8, ebusd
> address 36: slave #8, ebusd
> 
> root@raspberrypi:~# ebusctl scan result
> 08;Vaillant;BAI00;0600;5502
> 15;Vaillant;47000;0130;6002;21;12;49;0020108131;0082;011388;N2
