### ISSUE TITLE
Device not starting

### ISSUE THREAD

**Issue by realrewa** [danielkucera/esp-arduino-ebus#82]
Hi!
While powered via usb, 3.3v pin has 3.3v.
While connected to ebus, same pin has 2.7v, esp led no active, device not starting.
D1 led blinking with d7 at same time.
Ebus voltage 21.7v while not connected, 20.7v with connected device.
Any help will be appreciated.

**Comment by danielkucera** [comment]
Hi @realrewa ,
most likely, this is your issue: https://github.com/danielkucera/esp-arduino-ebus?tab=readme-ov-file#the-adapter-is-loosing-connectivity-breaking-other-ebus-components-communication-d7-is-blinking-wifi-is-disappearing-after-connecting-devices-on-the-bus-show-error-status-or-other-intermittent-failures

You probably need to power the adapter using USB, as the bus cannot supply enough power.

**Comment by realrewa** [comment]
Sorry, missed ebus-vcc jumper from readme. All works fine. Thank you!
