### ISSUE TITLE
static ip

### ISSUE THREAD

**Issue by ilgio** [danielkucera/esp-arduino-ebus#83]
How can I configure static IP?

**Comment by danielkucera** [comment]
Hi @ilgio ,
this is currently not possible or planned but I'll keep this issue open to possibly reevaluate in the future.

**Comment by danielkucera** [comment]
It has been implemented in #85 thanks to @yuhu-  :pray: , you can test by downloading artifact from here: https://github.com/danielkucera/esp-arduino-ebus/pull/85/checks
